-- JoinColumn
create table child (id integer generated by default as identity, primary key (id));
create table mother (id integer generated by default as identity, child_id integer, primary key (id));

-- mother has foreign key
alter table if exists mother drop constraint if exists child_id_fk;
alter table if exists mother add constraint child_id_uq unique (child_id);
alter table if exists mother add constraint child_id_fk foreign key (child_id) references child;

